### ISSUE TITLE
UI Internal Error after direct database inserts

### ISSUE THREAD

**Issue by StylesTrip** [jze/wikibase-insert#2]
Ran into this issue after running the code to insert items into the database and attempting to view the items in the UI.
Calling: http://localhost:8181/wiki/Item:Q288
Results:
`[4d31fd50f6106e4d332eba51] /wiki/Item:Q288 RuntimeException from line 105 of /var/www/html/extensions/Wikibase/repo/includes/Content/DeferredDecodingEntityHolder.php: Deferred decoding resulted in an incompatible entity, expected property, got item`

It seems like the loaded item is not in the correct format based on the error message?

However, when using the SpecialEntity:Data endpoint, it is able to retrieve the added items information and return it in JSON format.

Calling: http://localhost:8181/wiki/Special:EntityData/Q288.json
Results:
`{"entities":{"Q288":{"pageid":493,"ns":120,"title":"Item:Q288","lastrevid":1969,"modified":"2020-07-20T13:38:48Z","type":"item","id":"Q288","labels":{"en":{"language":"en","value":"Test 1"}},"descriptions":{"en":{"language":"en","value":"Test 1"}},"aliases":[],"claims":{"P204":[{"mainsnak":{"snaktype":"value","property":"P204","datavalue":{"value":"1","type":"string"},"datatype":"external-id"},"type":"statement","id":"Q288$e8ebc03e-fd21-4303-8257-c2af44a30d30","rank":"normal"}],"P5":[{"mainsnak":{"snaktype":"value","property":"P5","datavalue":{"value":{"entity-type":"item","numeric-id":287,"id":"Q287"},"type":"wikibase-entityid"},"datatype":"wikibase-item"},"type":"statement","id":"Q288$aa06b2d3-2ad9-4b96-bac5-dd7f54715c5d","rank":"normal"}]},"sitelinks":[]}}}`

Running versions:
MediaWiki | 1.33.2
PHP | 7.2.27 (apache2handler)
MariaDB | 10.3.22-MariaDB-1:10.3.22+maria~bionic
ICU | 63.1
Lua | 5.1.5

**Comment by jze** [comment]
I have not been able to reproduce the problem. The error message *expected property, got item* seems interesting to me. Did you create an **item** with the name `test entry` and two **properties** with the names `instance of` and `my property`? The first three lines of my Java debug output look like:

```
13:17:57.277 [net.genealogy.wikibase.Performance.main()] DEBUG net.genealogy.wikibase.Performance - Using P1 as the instance-of property.
13:17:57.280 [net.genealogy.wikibase.Performance.main()] DEBUG net.genealogy.wikibase.Performance - Using P2 as the data property.
13:17:57.280 [net.genealogy.wikibase.Performance.main()] DEBUG net.genealogy.wikibase.Performance - Using Q1 as the type item.
```

**Comment by StylesTrip** [comment]
Yes, I did. However, the difference is that I loaded other properties before that. It seems like if I have a clean instance this works...but if I have other properties and items in Wikibase and then try this I get the error.

Edit:
Adding some additional printlns I threw in to try and help debug:
```
16:57:07.058 [main] DEBUG net.genealogy.wikibase.Performance - Using P1 as the instance-of property.
Using term number: 2
16:57:07.061 [main] DEBUG net.genealogy.wikibase.Performance - Using P2 as the data property.
Using term number: 1
16:57:07.063 [main] DEBUG net.genealogy.wikibase.Performance - Using Q1 as the type item.
Inside runWithoutTransaction
16:57:07.066 [main] INFO net.genealogy.wikibase.Performance - Creating 1 items without a transaction...
```

Also added to executeUpdate method:
```
com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO text VALUES(5,'{"aliases":[],"claims":{"P1":[{"mainsnak":{"datavalue":{"type":"wikibase-entityid","value":{"entity-type":"item","numeric-id":1,"id":"Q1"}},"property":"P1","snaktype":"value"},"rank":"normal","id":"Q2$a853e904-e308-4f57-af35-84529c43e909","type":"statement"}],"P2":[{"mainsnak":{"datavalue":{"type":"string","value":"1"},"property":"P2","snaktype":"value"},"rank":"normal","id":"Q2$24b474c2-32ba-4dd6-b111-b4735a621c48","type":"statement"}]},"sitelinks":[],"id":"Q2","type":"item","descriptions":{"en":{"language":"en","value":"Test 1"}},"labels":{"en":{"language":"en","value":"Test 1"}}}','utf-8')
com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO page VALUES(5,120,'Q2','',0,0,rand(1),'20200723165707','20200723165707',5,589,'wikibase-item',NULL)
com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO revision VALUES(5,5,5,'',0,'','20200723165707',0,0,589,0,'4qv74cyqr8fdewb1h0psblusiiw93mo',NULL,NULL)
com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO comment VALUES(5,489980917,'/* wbeditentity-create:2|de */ Q2',NULL)
com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO revision_comment_temp VALUES (5,5)
com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO revision_actor_temp VALUES( 5, 1, '20200723165707',  5)
Using preselectIds
com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO content VALUES( 5 ,589,'4qv74cyqr8fdewb1h0psblusiiw93mo', 2, 'tt:5')
com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO slots VALUES( 5, 1, 5, 5)
com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO recentchanges VALUES ( 0,'20200723165707',0,'',1,120,'Q2',5,0,0,1,5,5,0,1,'mw.new',0,'127.0.0.1',0,589,0,0,NULL,'',''  )
com.mysql.cj.jdbc.ClientPreparedStatement: UPDATE wb_id_counters SET id_value=2 WHERE id_type='wikibase-item'
```

**Comment by jze** [comment]
I thing I found the problem. In my experiments the `model_id` for `wikibase-item` (in table `content_models`) was 2. However, sometimes it is 3. Maybe it depends on order you create your first item or property. Until I have added a real fix (with a look-up) to the program you can simply change the number in `DatabaseInsert.java` 
```sql
INSERT INTO content VALUES( ? ,?,?, 2, ?) 
```
to 3.

**Comment by jze** [comment]
Now the correct content model is read from the database or a new content model will be created if none exists.
